"use client";

import type { NextPage } from "next";
import Head from "next/head";

import { repository } from "./../package.json";

const weekdayStrings = [
  "Montag",
  "Dienstag",
  "Mittwoch",
  "Donnerstag",
  "Freitag",
];

const Home: NextPage<{
  days: string[][][];
  weekDateRange: string;
  timestamp: string;
}> = ({ days, weekDateRange, timestamp }) => {
  return (
    <div className="container mx-auto p-4">
      <Head>
        <title>Marienhof Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <h1 className="text-3xl text-center">🧑🏼‍🍳 Marienhof Menu 🧑🏼‍🍳</h1>

      <div className="md:w-3/4 mx-auto my-8">
        <h2>Menü für {weekDateRange}</h2>
        {days.map((day, dayIndex) => (
          <div key={dayIndex}>
            <h2 className="text-2xl pt-2">{weekdayStrings[dayIndex]}</h2>
            {day.map(([name, price], menuIndex) => (
              <div key={menuIndex} className="flex justify-between">
                <div>{name}</div>
                <div className="ml-2 flex-none text-right">€ {price}</div>
              </div>
            ))}
          </div>
        ))}

        <div className="flex-1 text-gray-400 pt-4 text-xs">
          Last generated: {timestamp}
        </div>
      </div>

      <div className="fixed bottom-0 left-0 right-0 text-center p-2 bg-gray-100">
        Developed with ❤️ in Vienna -{" "}
        <a
          className="underline decoration-sky-500 semi-bold hover:text-sky-500"
          href={repository}
          rel="noreferrer"
          target="_blank"
        >
          GitHub
        </a>
      </div>
    </div>
  );
};

export default Home;
