import { Analytics } from "@vercel/analytics/react";
import { Rubik_Distressed, Work_Sans } from "next/font/google";

import "./global.css";

const rubik = Rubik_Distressed({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-rubik",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-workSans",
});

export default function RootLayout({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>I am hungry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />

        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
      </head>
      <body className={`${rubik.variable} ${workSans.variable} font-body`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
