import { Analytics } from "@vercel/analytics/react";
import { Rubik_Dirt as Rubik, Work_Sans as WorkSans } from "next/font/google";
import { cookies } from "next/headers";

import "./global.css";

import ThemeToggle from "../components/ThemeToggle";
import pgk from "../package.json";
import { Suspense } from "react";

const { repository } = pgk;

const rubik = Rubik({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-rubik",
});

const workSans = WorkSans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-workSans",
});

async function saveSettings({ theme }: { theme: string }) {
  "use server";

  (await cookies()).delete({
    name: "theme",
    httpOnly: false,
    path: "/",
  });

  return {
    theme,
  };
}

export default async function RootLayout({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>I am hungry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function(){
              var hookValue = window.localStorage.getItem('usehooks-ts-dark-mode');

              if(hookValue === 'false') {
                return;
              }

              if(!hookValue && window.matchMedia('(prefers-color-scheme: light)').matches) {
                return;
              }

              var htmlElement = document.querySelector('html');
              htmlElement.classList.add('dark');
            })()
            `,
          }}
        />
      </head>
      <body
        className={`${rubik.variable} ${workSans.variable} font-body dark:bg-slate-800 dark:text-gray-50`}
      >
        <ThemeToggle onSaveSettings={saveSettings} />
        <Suspense fallback={<p>Loading ...</p>}>{children}</Suspense>
        <div className="fixed bottom-0 left-0 right-0 bg-gray-100 p-2 text-center dark:bg-slate-900">
          Developed with ❤️ in Vienna -
          <a
            className="semi-bold pl-1 underline decoration-sky-500 hover:text-sky-500"
            href={repository}
            rel="noreferrer"
            target="_blank"
          >
            GitHub
          </a>
        </div>
        <Analytics />
      </body>
    </html>
  );
}
