import { Analytics } from "@vercel/analytics/react";
import { Rubik_Dirt as Rubik, Work_Sans as WorkSans } from "next/font/google";

import "./global.css";

import ThemeToggleWrapper from "../components/ThemeToggleWrapper";
import pgk from "../package.json";

const { repository } = pgk;

const rubik = Rubik({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-rubik",
});

const workSans = WorkSans({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-workSans",
});

export default async function RootLayout({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>I am hungry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />

        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
      </head>
      <body
        className={`${rubik.variable} ${workSans.variable} font-body dark:bg-slate-800 dark:text-gray-50`}
      >
        <ThemeToggleWrapper />
        {children}
        <div className="fixed bottom-0 left-0 right-0 text-center p-2 bg-gray-100 dark:bg-slate-900">
          Developed with ❤️ in Vienna -
          <a
            className="underline decoration-sky-500 semi-bold hover:text-sky-500 pl-1"
            href={repository}
            rel="noreferrer"
            target="_blank"
          >
            GitHub
          </a>
        </div>
        <Analytics />
      </body>
    </html>
  );
}
