"use client";

import React from "react";

import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { repository } from "../package.json";

import { isProduction } from "./../utils/env";

const weekdayStrings = [
  "Montag",
  "Dienstag",
  "Mittwoch",
  "Donnerstag",
  "Freitag",
];

const Home: NextPage<{
  days: string[][][];
  weekDateRange: string;
  timestamp: string;
  title: string;
  emoji: string;
  telNumber?: string;
  menuRenderer: (menu: string[]) => React.ReactElement;
}> = ({
  days,
  weekDateRange,
  timestamp,
  title,
  emoji,
  telNumber,
  menuRenderer,
}) => {
  return (
    <div className="container mx-auto p-3">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="md:w-3/4 mx-auto mb-8">
        <div className="mb-2 md:mb-8 relative grid grid-rows-[42px_1fr] gap-2 md:grid-rows-none md:grid-cols-[80px_1fr_80px]">
          <Link
            className="border rounded-md p-2 border-gray-200 hover:border-gray-500 inline-block w-[80px]"
            href={isProduction ? "https://iamhungry.vercel.app" : "/"}
          >
            👈🏻 back
          </Link>
          <h1 className="text-3xl text-center font-heading">
            {emoji} {title} {emoji}
          </h1>
        </div>

        <div className="flex justify-between items-center">
          <h2>Menü für {weekDateRange}</h2>
          {telNumber ? (
            <a
              href={`tel:${telNumber}`}
              className="semi-bold p-2 border border-sky-100 rounded-md hover:border-sky-300 active:bg-slate-200"
            >
              ☎️ Call
            </a>
          ) : undefined}
        </div>
        {days.map((day, dayIndex) => (
          <div key={dayIndex}>
            <h2 className="text-2xl pt-2 font-heading">
              {weekdayStrings[dayIndex]}
            </h2>
            {day.map((menu, menuIndex) => (
              <div key={menuIndex} className="flex justify-between">
                {menuRenderer(menu)}
              </div>
            ))}
          </div>
        ))}

        <div className="flex-1 text-gray-400 pt-4 text-xs">
          Last generated: {timestamp}
        </div>
      </div>

      <div className="fixed bottom-0 left-0 right-0 text-center p-2 bg-gray-100">
        Developed with ❤️ in Vienna -
        <a
          className="underline decoration-sky-500 semi-bold hover:text-sky-500 pl-1"
          href={repository}
          rel="noreferrer"
          target="_blank"
        >
          GitHub
        </a>
      </div>
    </div>
  );
};

export default Home;
