"use client";

import React from "react";

import type { NextPage } from "next";
import Head from "next/head";

import { repository } from "../package.json";

const weekdayStrings = [
  "Montag",
  "Dienstag",
  "Mittwoch",
  "Donnerstag",
  "Freitag",
];

const Home: NextPage<{
  days: string[][][];
  weekDateRange: string;
  timestamp: string;
  title: string;
  emoji: string;
  telNumber?: string;
  menuRenderer: (menu: string[]) => React.ReactElement;
}> = ({
  days,
  weekDateRange,
  timestamp,
  title,
  emoji,
  telNumber,
  menuRenderer,
}) => {
  return (
    <div className="container mx-auto p-4">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <h1 className="text-3xl text-center">
        {emoji} {title} {emoji}
      </h1>

      <div className="md:w-3/4 mx-auto my-8">
        <div className="flex justify-between items-center">
          <h2>Menü für {weekDateRange}</h2>
          {telNumber ? (
            <a
              href={`tel:${telNumber}`}
              className="semi-bold p-2 border border-sky-100 rounded-md hover:border-sky-300 active:bg-slate-200"
            >
              ☎️ Call
            </a>
          ) : undefined}
        </div>
        {days.map((day, dayIndex) => (
          <div key={dayIndex}>
            <h2 className="text-2xl pt-2">{weekdayStrings[dayIndex]}</h2>
            {day.map((menu, menuIndex) => (
              <div key={menuIndex} className="flex justify-between">
                {menuRenderer(menu)}
              </div>
            ))}
          </div>
        ))}

        <div className="flex-1 text-gray-400 pt-4 text-xs">
          Last generated: {timestamp}
        </div>
      </div>

      <div className="fixed bottom-0 left-0 right-0 text-center p-2 bg-gray-100">
        Developed with ❤️ in Vienna -
        <a
          className="underline decoration-sky-500 semi-bold hover:text-sky-500 pl-1"
          href={repository}
          rel="noreferrer"
          target="_blank"
        >
          GitHub
        </a>
      </div>
    </div>
  );
};

export default Home;
