name: Update every monday morning
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5,8 * * 1"

jobs:
  run-updater:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: REST API with curl
      env:
         MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
      run: |
        curl -X GET "https://marienify.vercel.app/"
